### ISSUE TITLE
Using SymfonyHttpClient per instructions results in "cacert.pem file not found" fatal error.

### ISSUE THREAD

**Issue by dtrenz** [chriswoodford/foursquare-php#12]
I'm trying to use this inside of a Laravel application, so I opted for the SymfonyHttpClient, but I'm getting a cacert.pem error.  What am I missing?

**Comment by dtrenz** [comment]
I see now that, since the SymfonyHttpClient simply extends the CurlHttpClient, I still need to pass in the cacert.pem path on instantiation.  I would consider adding that to the README.  Thanks

$client = new \TheTwelve\Foursquare\HttpClient\SymfonyHttpClient($pathToCertificateFile);

**Comment by chriswoodford** [comment]
thanks for the heads up here! I've updated the README file

**Comment by yashaswini** [comment]
Hello All, 
i see Class SymphonyHttpClient not found error when i set that as my client. I am giving .pem file path to it too. 
 Could you help me with this?

**Comment by chriswoodford** [comment]
That error sounds more like an issue with the auto loading than with the pem file. Are you requiring vendor/autoload.php properly? Was the composer install process successful?
