### ISSUE TITLE
Client always instantiated with latest version of the Foursquare API

### ISSUE THREAD

**Issue by octopi** [chriswoodford/foursquare-php#8]
You ought to pick a date and stick with it. By always using today's date as the [version](https://developer.foursquare.com/overview/versioning) you're passing to Foursquare (https://github.com/chriswoodford/foursquare-php/blob/a564d1357515182829186a976d3548028d475c42/lib/TheTwelve/Foursquare/EndpointGateway.php#L103), you run the risk of bumping into breaking JSON changes that your app may not handle.

**Comment by chriswoodford** [comment]
thanks for the heads up!
